freeats/freeats

.github/workflows/production_deploy.yml
test/lint/eslint_test.rb
test/lint/rubocop_test.rb
test/lint/slim_lint_test.rb

Fix: rename branch

---

app/assets/javascript/controllers/reassignment_buttons_controller.js
app/assets/stylesheets/src/shared/_components.scss
app/assets/stylesheets/src/shared/_profile.scss
app/assets/stylesheets/src/shared/_scaffolds.scss
app/components/icon_component.rb
app/helpers/ats/positions_helper.rb
app/helpers/ats/tasks_helper.rb
app/helpers/pictures_helper.rb
app/views/ats/candidates/_action_buttons.html.slim
app/views/ats/candidates/_avatar_image.html.slim
app/views/ats/email_messages/_email_message.html.slim
app/views/ats/placements/_disrequalify_buttons.html.slim
app/views/ats/positions/_header_show.html.slim
app/views/ats/settings/_account_avatar.html.slim
app/views/shared/profile/_reassign_button.html.slim

fix(tabler): Icon/IconButton/Button with icon styles adapted for a tabler

---

app/views/ats/placements/_placement.html.slim

fix(candidates): forgotten name value pair for a reserve button

---

config/environments/development.rb
config/environments/production.rb

Add secret from envs

---

.github/workflows/production_deploy.yml

Use old name

---

app/assets/javascript/controllers/multiple_select_component_controller.js
app/assets/javascript/controllers/turbo_modal_tasks_controller.js
app/controllers/ats/tasks_controller.rb
app/helpers/ats/tasks_helper.rb
app/views/ats/tasks/_main_content.html.slim
app/views/ats/tasks/_new.html.slim
app/views/ats/tasks/_show.html.slim

Adapt select component for task modals

---

app/assets/stylesheets/src/shared/_scaffolds.scss

fix(ui): tabler line height for body set to 1.5

---

.github/workflows/production_deploy.yml

Change branch name for deploy

---

.github/workflows/production_deploy.yml

Fix: move branch name

---

app/assets/javascript/controllers/copy_to_clipboard_controller.js
app/assets/stylesheets/src/shared/_components.scss
app/assets/stylesheets/src/shared/_scaffolds.scss
app/components/icon_component.rb
app/helpers/ats/positions_helper.rb
app/views/ats/candidates/_header_show.html.slim
app/views/ats/positions/_header_show.html.slim
app/views/shared/note_threads/_note_thread.html.slim
app/views/shared/profile/_card_empty.html.slim

fix(ui): tabler icons after testing

---

app/assets/stylesheets/src/shared/_profile.scss

fix(ui): use white background color for tabler accordions

---

app/assets/stylesheets/src/ats/_positions.scss
app/assets/stylesheets/src/shared/_profile.scss
app/grids/ats/candidates_grid.rb
app/grids/ats/dashboard_candidates_grid.rb
app/grids/ats/team_grid.rb
app/helpers/pictures_helper.rb
app/views/ats/candidates/_avatar_image.html.slim
app/views/ats/candidates/_candidate_files.html.slim
app/views/ats/members/_member_element.html.slim
app/views/ats/placements/_placement_pipeline_card.html.slim
app/views/ats/settings/_account_avatar.html.slim
app/views/ats/tasks/_main_content.html.slim
app/views/layouts/ats/_navbar.html.slim
app/views/shared/notes/_note_edit.html.slim
app/views/shared/notes/_note_show.html.slim
app/views/shared/profile/_notes.html.slim
app/views/shared/profile/_reassign_button.html.slim

fix(ui): all avatars use `avatar` class and correct sizes

---

app/assets/javascript/src/shared/confirmations.js
app/assets/stylesheets/src/shared/_components.scss
app/components/button_component.rb

feat(ui): new cancel button style

---

app/assets/stylesheets/src/ats/_positions.scss
app/views/ats/positions/pipeline_tab.html.slim

fix(ui): pipeline styles adapted to a tabler

---

app/views/career_site/positions/show.html.slim

fix(career_site): don not display location for non-open positions

---

app/assets/stylesheets/src/shared/_components.scss

fix(style): Returned .text-input-component-disabled style

---

app/views/career_site/positions/show.html.slim

fix(ui): Fixed apply button placement

---

app/assets/stylesheets/src/shared/_scaffolds.scss
app/views/layouts/_footer.html.slim

fix(style): Changed footer text style

---

app/controllers/career_site/positions_controller.rb
app/views/career_site/positions/index.html.slim
app/views/career_site/positions/show.html.slim
config/locales/career_site.en.yml

fix(style): Career site fixes positions page

---

app/assets/stylesheets/src/shared/_components.scss

fix(ui): add gap for select input only when at least 1 item is present

---

app/controllers/ats/tasks_controller.rb
app/grids/ats/profile_tasks_grid.rb
app/grids/ats/tasks_grid.rb

fix: order on task grid

---

app/assets/stylesheets/src/shared/_navbar.scss
app/views/layouts/ats/_navbar.html.slim

fix(ui): adapt navbar

---

app/assets/stylesheets/src/ats/_positions.scss
app/assets/stylesheets/src/shared/_scaffolds.scss
app/views/ats/candidates/_avatar_image.html.slim
app/views/ats/placements/_placement_pipeline_card.html.slim
app/views/ats/settings/_account_avatar.html.slim

fix(avatars): new avatar size class and its usage

---

app/views/ats/positions/_suggestion.html.slim
config/locales/en.yml

feat(ui): added tool-tips on quick assignment buttons on Candidate page

---

app/assets/javascript/controllers/html_select_component_controller.js
app/assets/javascript/controllers/multiple_select_component_controller.js
app/assets/javascript/controllers/pill_select_component_controller.js
app/assets/javascript/controllers/single_select_component_controller.js
app/assets/stylesheets/src/shared/_components.scss
app/components/html_select_component.rb
app/components/multiple_select_component.rb
app/components/pill_select_component.rb
app/components/select_component.rb
app/components/single_select_component.rb
package.json
yarn.lock

Closes #40.
**DO NOT FORGET** to update selectize package after merging this [pr](https://github.com/toughbyte/selectize.js/pull/23)

fix(ui): display arrow only for local select fields

---

app/assets/stylesheets/src/shared/_components.scss
app/assets/stylesheets/src/shared/_scaffolds.scss

fix(tabler): css variables for shadows set to none

---

lib/tasks/disqualify_reasons.rake

feat(disqualify_reason): update populate_disqualify_reasons rake task

---

app/controllers/ats/positions_controller.rb

feat(ui): change order of users to alphabetical for positions assignee selects

---

app/assets/stylesheets/src/shared/_profile.scss

fix(ui): candidate placement button group old styles

---

app/grids/ats/candidates_grid.rb
app/grids/ats/dashboard_candidates_grid.rb
app/grids/ats/team_grid.rb
app/helpers/ats/members_helper.rb
app/helpers/pictures_helper.rb
app/views/ats/members/_member_element.html.slim
app/views/ats/placements/_placement_pipeline_card.html.slim
app/views/ats/quick_search/_candidate_element.html.slim
app/views/ats/tasks/_main_content.html.slim
app/views/layouts/ats/_navbar.html.slim
app/views/shared/notes/_note_edit.html.slim
app/views/shared/notes/_note_show.html.slim
app/views/shared/profile/_notes.html.slim
app/views/shared/profile/_reassign_button.html.slim

fix(ui): set correct avatar size for recruiter select

---

app/views/layouts/career_site/_footer.html.slim

fix(ui): removed extra spacing on the right on 320px dimension on career site

---

app/assets/stylesheets/src/career_site/_main.scss

fix(ui): reduces content max width to 740px on career site

---

app/assets/stylesheets/src/career_site/_main.scss
app/views/career_site/positions/index.html.slim

fix(ui): fixed position block on positions page 

---

app/assets/stylesheets/src/shared/_profile.scss
app/assets/stylesheets/src/shared/_scaffolds.scss
app/views/ats/candidates/_profile.html.slim
app/views/ats/positions/_profile.html.slim
app/views/ats/tasks/_show.html.slim
app/views/layouts/ats/profile.html.slim

fix(ui): adapt tabs styles

---

app/assets/stylesheets/src/shared/_profile.scss
app/assets/stylesheets/src/shared/_scaffolds.scss
app/helpers/scorecards_helper.rb
app/views/ats/scorecards/_form.html.slim
config/locales/en.yml

fix(ui): scorecards button layout and new colors

---

app/assets/stylesheets/src/shared/_scaffolds.scss
app/views/ats/dashboard/index.html.slim

fix(dashborad): new typography line-height, font-size

---

app/controllers/ats/candidates_controller.rb
app/models/location.rb
app/queries/base_queries.rb

refact: Renamed HubQueries class to BaseQueries

---

app/assets/stylesheets/src/ats/_main.scss
app/assets/stylesheets/src/shared/_scaffolds.scss
app/views/career_site/positions/show.html.slim
config/locales/career_site.en.yml

fix(ui): career site fixes on position page

---

app/assets/stylesheets/entrypoints/career_site.scss
app/assets/stylesheets/src/ats/_recaptcha.scss
app/assets/stylesheets/src/career_site/_main.scss

feat(ui): Hidden recaptcha badge on register page

---

app/views/ats/tasks/_change_status_control.html.slim
app/views/ats/tasks/_main_content.html.slim
app/views/datagrid/_enum_checkboxes.html.erb

fix(ui): checkboxes app wide 

---

app/assets/stylesheets/src/ats/_main.scss
app/assets/stylesheets/src/shared/_profile.scss
app/views/ats/positions/pipeline_tab.html.slim
app/views/ats/tasks/_show.html.slim
app/views/shared/note_threads/_note_thread.html.slim

fix(ui): notes styles

---

app/assets/stylesheets/src/career_site/_main.scss
app/controllers/application_controller.rb
app/controllers/career_site/positions_controller.rb
app/views/layouts/career_site/_footer.html.slim
config/locales/career_site.en.yml

feat(career_site): added links to ToS and Privacy Policy on Career Site

---

app/assets/stylesheets/src/shared/_scaffolds.scss
app/helpers/pictures_helper.rb
app/views/ats/candidates/_candidate_files.html.slim

fix(ui): candidate files table now looks like the other ones

---

app/assets/stylesheets/src/shared/_datagrid.scss
app/assets/stylesheets/src/shared/_scaffolds.scss
app/views/datagrid/_head.html.erb
app/views/datagrid/_order_for.html.erb

feat(grids): sorting tabler arrows

---

.github/workflows/conventional_commits.yml

ci: conventional commits PR name checker

---

app/assets/stylesheets/src/ats/_main.scss
app/helpers/application_helper.rb

fix(ui): form control focus style is back

---

app/assets/stylesheets/src/shared/_datagrid.scss

fix(ui): removed underline for lables headings with links

---

app/views/ats/tasks/_main_content.html.slim

fix(ui): task name now centered

---

app/controllers/ats/placements_controller.rb
app/grids/ats/candidates_grid.rb
app/grids/ats/dashboard_candidates_grid.rb
app/helpers/candidates_grid_helper.rb
app/helpers/candidates_helper.rb
app/models/placement.rb
app/models/tenant.rb
app/operations/placements/change_status.rb
app/views/ats/placements/_disrequalify_buttons.html.slim
app/views/ats/placements/_placement.html.slim
app/views/ats/positions/_suggestion.html.slim
config/locales/en.yml
db/migrate/20241107081744_update_placement_statuses.rb
db/structure.sql
test/fixtures/disqualify_reasons.yml
test/fixtures/placements.yml
test/grids/ats/candidates_grid_test.rb
test/models/placement_test.rb
test/operations/placements/change_status_test.rb

Part of #44.
rake task `disqualify_reasons:populate_disqualify_reasons` should be executed before merging this PR.

feat(disqualify_reason): update placements logic and views

---

app/assets/stylesheets/src/shared/_components.scss
app/helpers/ats/positions_helper.rb

refactor: tabler gray-500 color for icon button ghost and draft position

---

app/assets/stylesheets/src/career_site/_main.scss
app/views/career_site/positions/show.html.slim
app/views/layouts/career_site/application.html.slim

refactor(career site): career site color changes

---

app/controllers/ats/placements_controller.rb

chore: added comment for rubocop

---

app/views/ats/candidates/_header_edit.html.slim

fix(ui): adapt blacklisted checkbox to tabler

---

app/assets/stylesheets/src/shared/_profile.scss
app/helpers/candidates_helper.rb
app/views/ats/candidates/activities_tab.html.slim
app/views/ats/positions/activities_tab.html.slim
app/views/ats/tasks/_activity_event_row.html.slim
app/views/ats/tasks/_show.html.slim
app/views/kaminari/ats/_paginator.html.slim
test/controllers/ats/candidates_controller_test.rb
test/controllers/positions_controller_test.rb

fix(ui): activities list-group became tabler activity

---

app/assets/stylesheets/entrypoints/component_preview.scss
app/assets/stylesheets/src/shared/_components.scss

Closes #177.
- background-color
-  border-color
- text color
- focus shadow color
- focus border color
- placeholder color

fix(ui): apply Tabler's styles for select input

---

app/assets/javascript/controllers/note_thread_controller.js
app/assets/javascript/controllers/notes_controller.js
app/helpers/note_threads_helper.rb
app/views/shared/note_threads/_note_thread.html.slim

Closes #150.
Copied solution from internal project:
https://github.com/toughbyte/hub/pull/15682
https://github.com/toughbyte/hub/pull/15788
https://github.com/toughbyte/hub/pull/15797

fix(ui): note thread collapse button

---

app/views/ats/positions/activities_tab.html.slim
app/views/kaminari/ats/_paginator.html.slim

fix(ui): paginator `klass` option rename and became optional

---

app/helpers/candidates_helper.rb
app/misc/rodauth_main.rb
app/models/tenant.rb
app/operations/tenants/add.rb
config/locales/en.yml

Closes #44.
rake task `events:update_placement_changed_events` should be executed before merging this PR

chore: cleaned leftovers after customize disqualify reason

---

app/assets/stylesheets/src/shared/_profile.scss
app/controllers/ats/candidates_controller.rb

fix(ui): missed anchor target effect for activity

---

app/assets/stylesheets/src/career_site/_main.scss

fix(ui): updated top-padding for main container

---

app/assets/stylesheets/src/shared/_datagrid.scss
app/views/ats/candidates/activities_tab.html.slim
app/views/kaminari/ats/_page.html.slim
app/views/kaminari/ats/_paginator.html.slim

fix(ui): pagination active page styles

---

app/assets/stylesheets/entrypoints/ats.scss
app/assets/stylesheets/entrypoints/career_site.scss
app/assets/stylesheets/src/shared/_recaptcha.scss
app/views/career_site/positions/show.html.slim
app/views/rodauth/create_account.html.slim

fix: updated line-height for recaptcha text

---

app/assets/stylesheets/src/career_site/_main.scss

feat: Removed footer height ccs on career site

---

app/assets/stylesheets/src/shared/_scaffolds.scss

Since navbar is always 56px, the variable should be 56px as well

fix(ui): navbar height variable change `53px` -> `56px`

---

app/components/button_component.rb
app/views/ats/positions/pipeline_tab.html.slim

fix(ui): alignment of tab pipeline button

---

app/assets/stylesheets/src/shared/_scaffolds.scss
app/controllers/concerns/error_handler.rb
app/views/errors/403.html.slim
app/views/errors/404.html.slim
app/views/errors/422.html.slim
app/views/errors/500.html
app/views/errors/_button.html.slim
config/locales/en.yml
test/controllers/application_controller_test.rb

feat: new error pages

---

app/views/ats/candidates/_stage_scorecards.html.slim
app/views/ats/candidates/scorecards_tab.html.slim
test/controllers/ats/candidates_controller_test.rb

fix(ui): accordion styles on low res

---

app/views/errors/500.html

fix(ui): correct stroke-width for arrow icon on page 500

---

app/helpers/scorecards_helper.rb

refactor(ui/scorecards): color class for an icon only

---

app/assets/javascript/controllers/copy_to_clipboard_controller.js
app/assets/javascript/controllers/note_thread_controller.js
app/assets/javascript/src/shared/bootstrap_activators.js
deno.json
esbuild.config.mjs
eslint.config.mjs
package.json
yarn.lock

chore: eslint with extended config instead of deno fmt

---

app/assets/stylesheets/src/ats/_main.scss
app/assets/stylesheets/src/career_site/_main.scss
app/assets/stylesheets/src/shared/_scaffolds.scss
app/views/career_site/positions/show.html.slim

fix(career site): positions page apply form styles

---

app/assets/stylesheets/src/ats/_main.scss
app/views/ats/candidates/_header_edit.html.slim

fix: avatar edit padding on Candidate page on edit mode

---

app/assets/stylesheets/src/shared/_scaffolds.scss

fix(ui): ban (and some other icons) vertically aligned

---

app/helpers/ats/members_helper.rb
app/views/shared/profile/_reassign_button.html.slim

fix(assign recruiter select field): set active member to apply styles in dropdown

---

app/views/ats/settings/_account_avatar.html.slim
app/views/shared/profile/_image_delete_button.html.slim

fix(ui): buttons placement on settings for low resolutions

---

app/helpers/candidates_grid_helper.rb

fix(ui): set small size for ban icons on candidates grid

---

app/assets/stylesheets/src/shared/_profile.scss

fix(scorecards/ui): color `inherit` -> `--tblr-white` for selected option icon

---

app/views/ats/candidates/_profile.html.slim
app/views/ats/positions/_profile.html.slim

fix(profiles/ui): tabs button now component

---

app/views/rodauth/reset_password_request.html.slim

chore(reset password page): set correct back path

---

app/controllers/authorized_controller.rb
app/controllers/rodauth_controller.rb
app/misc/rodauth_app.rb
app/misc/rodauth_main.rb
config/routes.rb

refactor(authentication): move registered users logic from RodauthApp config to the authorized controller

---

app/helpers/cards_helper.rb
app/views/shared/profile/_card_edit.html.slim
app/views/shared/profile/_card_show.html.slim

fix(ui): Added truncate for card labels

---

app/assets/stylesheets/src/shared/_components.scss

feat(select component dropdown): add check icon for selected options

---

app/assets/stylesheets/src/shared/_components.scss

Closes #238.
Also refactored variables naming to take less space
https://github.com/user-attachments/assets/7ce96dcf-ea7e-48ee-ad20-9d2f6ac8d3b8

fix(ui): clarified select input padding to not overlap chevron

---

app/assets/stylesheets/src/shared/_components.scss

Closes #238.
forgot to set max-width to apply content truncating.
copied from the internal project.
https://github.com/user-attachments/assets/f26a2468-5817-479b-8c46-a94714a8acdd

fix(select input): truncate long content

---

app/assets/javascript/controllers/multiple_select_component_controller.js
app/assets/stylesheets/src/shared/_components.scss

Closes #250.
copied logic from [internal project](https://github.com/toughbyte/hub/pull/15709)

fix(multiple select input): do not display doubled dots

---

yarn.lock

related to https://github.com/toughbyte/selectize.js/pull/25

chore(core): update selectize

---

app/controllers/settings/company/general_profiles_controller.rb
app/policies/settings/company/general_profile_policy.rb
app/views/settings/company/general_profiles/_company_logo.html.slim
app/views/settings/company/general_profiles/_company_name.html.slim
app/views/settings/company/general_profiles/show.html.slim
app/views/settings/personal/profiles/show.html.slim
app/views/settings/shared/_settings_card.html.slim
app/views/settings/shared/_tabs.html.slim
config/locales/en.yml
config/routes.rb
test/controllers/settings/company/general_profiles_controller_test.rb

feat: Add general page in settings

---

app/models/email_template.rb
db/migrate/20241202095447_add_tenant_to_email_templates.rb
db/structure.sql
test/factories/email_template.rb
test/fixtures/email_templates.yml
test/models/tenant_test.rb

fix(core): add tenant to email templates

---

app/assets/javascript/controllers/enter_turbo_submit_controller.js
app/assets/javascript/controllers/input_utils_controller.js
app/assets/javascript/controllers/select_component_controller.js
app/assets/javascript/src/shared/input_utils.js
app/assets/stylesheets/src/ats/_candidate.scss
app/controllers/ats/compose_controller.rb
app/views/ats/email_messages/_email_compose_form.html.slim

fix(ui): styles for email compose form

---

app/views/layouts/action_text/contents/_content.html.erb
lib/tasks/events.rake
test/controllers/ats/scorecards_controller_test.rb
test/controllers/positions_controller_test.rb
test/operations/scorecards/change_test.rb

fix: trix content uses default layout 

---

app/assets/stylesheets/src/ats/_settings.scss
app/controllers/settings/company/general_profiles_controller.rb
app/controllers/settings/recruitment/email_templates_controller.rb
app/models/email_template.rb
app/policies/settings/recruitment/email_templates_policy.rb
app/views/settings/recruitment/email_templates/_form.html.slim
app/views/settings/recruitment/email_templates/new.html.slim
app/views/settings/recruitment/email_templates/show.html.slim
config/locales/en.yml
db/migrate/20241204053019_add_email_template_index_on_tenant_and_name.rb
db/migrate/20241204071813_add_default_value_for_email_template_subject.rb
db/structure.sql
test/controllers/settings/recruitment/email_templates_controller_test.rb
test/factories/email_template.rb
test/fixtures/action_text/rich_texts.yml
test/fixtures/email_templates.yml
test/models/email_template_test.rb
test/models/liquid_template_test.rb

feat(core): add logic to save and update email template

---

app/assets/stylesheets/src/ats/_candidate.scss
app/views/ats/email_messages/_email_compose_form.html.slim

fix(ui): small updates for email compose form

---

app/lib/rails_admin/config/actions/delete_account.rb
app/models/account.rb
app/models/member.rb
config/initializers/rails_admin.rb
config/locales/rails_admin.yml
test/models/account_test.rb

feat: add method to delete accounts to rails admin

---

app/views/layouts/ats/_alert.html.slim

fix(alert): update link place

---

app/views/shared/_notification.html.slim

fix(alert): link placement

---

app/models/position.rb
app/operations/candidates/change.rb
app/operations/positions/change_status.rb
test/controllers/positions_controller_test.rb

feat: auto disqualify/requalify candidates on closing position

---

app/controllers/application_controller.rb
app/views/layouts/ats/application.html.slim
app/views/layouts/career_site/application.html.slim

This reverts commit 7b2d79d99bc6eaf814dfc56d557b8bf985464c07.
Closes #.

revert: "feat: added clarity script (#90)"

---

app/assets/javascript/controllers/compose_controller.js
app/controllers/api/v1/email_templates_controller.rb
app/controllers/ats/compose_controller.rb
app/helpers/ats/emails_helper.rb
app/helpers/candidates_helper.rb
app/models/event.rb
app/models/liquid_template.rb
app/policies/api/v1/email_template_policy.rb
app/views/ats/email_messages/_email_compose_form.html.slim
app/views/ats/email_messages/_email_template_element.html.slim
config/routes.rb
db/migrate/20250225065941_add_transactional_email_sent_to_events.rb
db/structure.sql
test/controllers/api/v1/email_templates_controller_test.rb
test/fixtures/action_text/rich_texts.yml
test/models/liquid_template_test.rb

feat(core): Add select template to compose

---

app/assets/stylesheets/src/shared/_trix.scss
app/views/settings/recruitment/email_templates/_form.html.slim

fix(style): variables color and trix placeholder

---

app/grids/ats/dashboard_positions_grid.rb

fix(scope): Scoped order is ignored, it's forced to be batch order.

---

app/controllers/ats/candidates_controller.rb
config/locales/en.yml

fix(download): show error if CV was removed before downloading it

---

app/assets/stylesheets/src/shared/_datagrid.scss

fix(style): Avatar icon column became collapsed in candidates' grid

---

app/models/position.rb
app/views/ats/candidates/_display_inline.html.slim
test/factories/position.rb
test/models/position_test.rb

fix(core): Delete placement_removed events on deleting position
